[package]
name = "pathfinder-levels"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
wee_alloc = { version = "0.4.5", optional = true }

[profile.release]
opt-level = "s"

[features]
default = []